### PR TITLE
MUI. Unions [generated]

### PR DESCRIPTION
**Pull request by turansky**
cc @aerialist7

### CODE REVIEW

**Review by aerialist7 — APPROVED** [review]

**Review by aerialist7 — APPROVED** [review]

**Review by aerialist7 — APPROVED** [review]

**Comment by aerialist7** [comment]
Hi @Leonya, Happy New Year!
Could you please say in which time we can expect a first 2022 release? 🎄

**Comment by Leonya** [comment]
Happy New Year to you too! :) I can do it anytime, but maybe it makes sense to finish replacing `mui.system.Union` with proper enums first? There's still a few left.

**Comment by turansky** [comment]
Happy New Year!

+1 to @Leonya 
1 or 2 PRs planned for clear string unions

**Comment by turansky** [comment]
Clear string unions finished in #1087

**Pull request merged**
