### PR TITLE
Version property unification

### PR DESCRIPTION
**Pull request by turansky**
Common template - `$id.version`

| Dependency | `id` | Example |
| :--- | :---: | :--- |
|NPM| `$packageName`| `react-dom` | 
|Kotlin| `$projectId`| `kotlinx-html` | 
|Gradle plugin| `$name-plugin`| `bintray-plugin` | 

### Existed examples:
* [JUnit](https://github.com/junit-team/junit5/blob/master/gradle.properties)
* [JMeter](https://github.com/apache/jmeter/blob/master/gradle.properties)

### CODE REVIEW

**Comment by Leonya** [comment]
@turansky I have just noticed that there are lots of "Could not resolve project" errors when importing the project in IDEA (`1.4-js-jr` branch). It builds fine from the command line, but IDEA is unhappy. Please take a look.

**Comment by turansky** [comment]
@Leonya

Could you check IDEA with following versions in `gradle.properties`?
```
kotlin.version=1.3.71
kotlinx-html.version=0.7.1
kotlinx-coroutines.version=1.3.5
kotlinx-serialization.version=0.20.0
```

**Comment by turansky** [comment]
@Leonya 

IDEA unhappy
```
kotlin.js.compiler=legacy
```

IDEA happy
```
kotlin.js.compiler=legacy
```

Do you have same results?

**Comment by Leonya** [comment]
Yes, thanks.

**Comment by turansky** [comment]
[KT-38214](https://youtrack.jetbrains.com/issue/KT-38214)

**Pull request merged**
