### PR TITLE
DSL marker for `RProps`

### PR DESCRIPTION
**Pull request by turansky**
cc @sgrishchenko @aerialist7

### CODE REVIEW

**Review by aerialist7 — APPROVED** [review]

**Comment by Leonya** [comment]
This can't be merged in a foreseeable future, see https://github.com/JetBrains/kotlin-wrappers/commit/a61e27678cd01d73d100c0671cdecc4ff2d132ac

**Comment by turansky** [comment]
For now I know single root cause - invalid DSL (css in dom or dom in css)
Do you have other problems?

**Comment by Leonya** [comment]
In Space we have a concept of "live" properties. These can only be used in "trackable" contexts. Once you've added these annotations, all the places where we call "Property#live" inside a `css` block (perfectly valid!) became compilation errors. This is fixable, of course, and we are fixing it already for DOM builders by introducing a parallel hierarchy of classes, along the lines of `interface XStyledDOMBuilder<out T : Tag> : StyledDOMBuilder<T>, XTrackable` but this is not an elegant fix. Right not we don't want to add these hacks for CSS builders. Once Kotlin has multiple receivers this will become easy.

**Comment by turansky** [comment]
[Related Slack discussion](https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1628078963002700)

**Pull request closed without merging**
