### PR TITLE
Prepare for 1.4.0

### PR DESCRIPTION
**Pull request by ilgonmic**

### CODE REVIEW

**Comment by ilgonmic** [comment]
Seems problem with serialization, postponed temporarily

**Comment by Leonya** [comment]
I'm confused, should I merge it or not?

**Comment by ilgonmic** [comment]
Not yet, sorry :(
Found problem in kotlinx.serialization binaries, team is republishing it

**Comment by ilgonmic** [comment]
@Leonya Team told that serialization was republished (https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-core/1.0.0-RC/)
Can be merged now
Seems that version will be `pre.110-kotlin-1.4.0`
Please tell me, if you will release it, or I can release it by my own

**Comment by Leonya** [comment]
Thanks, I will release it

**Comment by Leonya** [comment]
Released `pre.110-kotlin-1.4.0`

**Pull request merged**
