### PR TITLE
enable Gradle Build Cache

### PR DESCRIPTION
**Pull request by aSemy**
[Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html) is a quick and easy way to improve build performance.

### CODE REVIEW

**Comment by hfhbd** [comment]
What about the CI too?

**Comment by turansky** [comment]
> What about the CI too?

@hfhbd Could you please elaborate?

**Comment by hfhbd** [comment]
@turansky Sure, you have to use the gradle build action to enable CI cache.
See https://github.com/hfhbd/bootstrap-compose/blob/aed535d3bcef444cf06c4838694acccad76f0d66/.github/workflows/CI.yml#L25 for implementation.

**Comment by aSemy** [comment]
> What about the CI too?

Good point, Build Cache support should be enabled on CI too.

For this PR I just wanted to enable it, and I'd like to make another PR to update the GitHub Workflows.

**Pull request merged**
