### PR TITLE
kotlin2js. Standard plugin configuration

### PR DESCRIPTION
**Pull request by turansky**
* Plugin in plugins DSL block
* Configuration via `plugins.withType`

### CODE REVIEW

**Comment by Leonya** [comment]
Please don't refactor build scripts, we are going to change them anyway when migrating to the new multiplatform plugin.

**Comment by turansky** [comment]
> Please don't refactor build scripts
Do you mean `master` branch only?

Can I fix errors in `1.4-js-ir`?

**Comment by Leonya** [comment]
> Do you mean master branch only?

Yes, these are outdated.

> Can I fix errors in 1.4-js-ir?

What errors do you mean?

**Comment by turansky** [comment]
> What errors do you mean?
`mavenLocal()` usage for example
Fixed here #160

**Pull request closed without merging**
