### PR TITLE
MUI Icons `5.2.0` [generated]

### LINKED ISSUE #986: [kotlin-mui] Icons are unusable
I tried using them via the `Icon` API, but just the text was displayed. I had to use `SvgIcon` and hardcode the SVG path:

```
        SvgIcon {
            path {
                attrs.d = "M9 16.17 4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"
            }
        }
```

### PR DESCRIPTION
**Pull request by turansky**
Fix #986

Count - `9888`

cc @aerialist7

### CODE REVIEW

**Review by aerialist7 — APPROVED** [review]
🔥

**Comment by Leonya** [comment]
> +88,997

Compilation is now 3 times slower 😅

**Comment by turansky** [comment]
Main root cause - slow IR compilation

**Comment by turansky** [comment]
https://youtrack.jetbrains.com/issue/KT-49949

**Pull request merged**
