### PR TITLE
Remove deprecated `useMemo` and `useCallback` signatures

### PR DESCRIPTION
**Pull request by turansky**
cc @sgrishchenko @aerialist7

### CODE REVIEW

**Comment by Leonya** [comment]
Can we wait, say, a month and then rename all deprecated signatures at once? I don't see the point in removing them one by one.

**Review by aerialist7 — APPROVED** [review]

**Comment by turansky** [comment]
OK. 26 august - "big cleanup" day

**Comment by Leonya** [comment]
Deal.

**Comment by Leonya** [comment]
Deal.

**Pull request closed without merging**
