### PR TITLE
Standard naming for `Context` types

### PR DESCRIPTION
**Pull request by turansky**
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/328064fd432eb99ecc442979b5c4fd5d299d50e6/types/react/index.d.ts#L375)

cc @sgrishchenko @aerialist7

### CODE REVIEW

**Comment by Leonya** [comment]
Please resolve conflicts.

**Comment by turansky** [comment]
Conflicts resolved

**Comment by Leonya** [comment]
Are you planning to rename RProps and RState as well?

**Comment by turansky** [comment]
Investigation required before `RProps` refactoring

**Comment by Leonya** [comment]
Released in pre.216

**Pull request merged**
