### PR TITLE
Toolbox icon

### PR DESCRIPTION
**Pull request by turansky**
Screenshot 2020-04-15 at 06 10 01
Screenshot 2020-04-15 at 06 11 36

### CODE REVIEW

**Comment by Leonya** [comment]
Added the icon to upsource.jetbrains.com as well :)

**Comment by turansky** [comment]
Do you have official Kotlin/JS logo?
This icon - icon from "Project View"

**Comment by Leonya** [comment]
I don't think we do.

**Comment by turansky** [comment]
> [we should probably ask designers to create one](https://github.com/JetBrains/kotlin/pull/3296#issuecomment-613998372)

**Pull request merged**
