### PR TITLE
Remove unused/invalid `author` property

### PR DESCRIPTION
**Pull request by turansky**
cc @aerialist7

### CODE REVIEW

**Comment by Leonya** [comment]
It's not unused or invalid, it's a must for Maven Central publication...

**Comment by Leonya** [comment]
You are right, it is unused, but it should be. Instead of deleting this property, the values should be propagated to POM files, I think.

**Comment by turansky** [comment]
Default `developers` section, like in [typical JetBrains libraries](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core/1.5.2/pom) looks more logically. 
Also in most cases we have no fixed developers list

**Comment by Leonya** [comment]
Released in pre.245

**Pull request merged**
