### PR TITLE
React Router: karakum.config.json is improved

### PR DESCRIPTION
**Pull request by sgrishchenko**

### CODE REVIEW

**Comment by turansky** [comment]
Where is valid folders (according packages)? :)

**Comment by sgrishchenko** [comment]
What do you mean saying "valid folders"? Folders for custom plugins? If so it is 
```
buildSrc/karakum/**/*.js
<projectDir>/karakum/**/*.js
```
by default but it is cofigurable

**Comment by Leonya** [comment]
The package is `remix.run.router`, so the path should be `src/main/generated/remix/run/router`.

**Comment by sgrishchenko** [comment]
I can fix it because of conversions in this repo but FYI https://kotlinlang.org/docs/coding-conventions.html#directory-structure
image

**Comment by sgrishchenko** [comment]
I have fixed file structure BTW.

**Pull request merged**
