### PR TITLE
CSSType. Remove unsafe factory methods

### PR DESCRIPTION
**Pull request by turansky**

### CODE REVIEW

**Comment by goncalossilva** [comment]
This also eliminates the single parameter Margin/Padding invocation. Is that expected?

**Comment by turansky** [comment]
@goncalossilva Which call do you mean?

**Comment by goncalossilva** [comment]
For example, `Margin(auto)` does not work. Only `Margin(auto, auto)`.

**Comment by turansky** [comment]
`margin = auto` :)

@sgrishchenko

**Comment by goncalossilva** [comment]
Oh. I didn't figure that one out! Thanks for sharing. :)

**Pull request merged**
