### PR TITLE
Declare versions in gradle.properties

### PR DESCRIPTION
**Pull request by turansky**
Part of #161

### CODE REVIEW

**Comment by Leonya** [comment]
Why? Declaring versions in `versions.gradle` is perfectly fine.

**Comment by turansky** [comment]
1. Applied automatically
2. Less groovy = simplify migration on Kotlin DSL
3. Looks like standard place for versions:
3.1. [JUnit](https://github.com/junit-team/junit5/blob/master/gradle.properties)
3.2. [arrow-kt](https://github.com/arrow-kt/arrow/blob/master/gradle.properties)
4. No recompilation required after `gradle.properties` change

**Comment by turansky** [comment]
@Leonya Will continue migration to Kotlin DSL?

**Comment by Leonya** [comment]
Yes, go ahead.

**Comment by turansky** [comment]
@Leonya, will you merge this PR?

**Pull request merged**
