### PR TITLE
Typesafe inline css

### PR DESCRIPTION
**Pull request by Jamdan2**
Adding this extension function allows for inline styles like in normal react, except typesafe. I have found it useful in one of my own projects. What do you think?

### CODE REVIEW

**Comment by Leonya** [comment]
@Hypnosphi are we OK with a dependency on kotlin-css in kotlin-react?

**Comment by Hypnosphi** [comment]
Not really. How could we avoid it?

**Comment by Leonya** [comment]
Well, we don't have to accept the PR as-is. We can simply add this helper function to the documentation. Alternatively, we could create a `kotlin-react-css-bridge` package, but that seems like too big a hassle for a utility function.

**Comment by Jamdan2** [comment]
I agree, it is an ugly dependency. Do you want me to add the function to the README instead?

**Comment by Leonya** [comment]
Yes, please.

**Pull request merged**
