### PR TITLE
Remove 'kotlin-css-js' NPM publishing

### PR DESCRIPTION
**Pull request by turansky**
Part of #201

### CODE REVIEW

**Comment by Leonya** [comment]
Does the new `kotlin-css` NPM package include both metadata and JS files? Because the _old_ one only contains metadata.

**Comment by Leonya** [comment]
And what about the other packages? If you take a look into build/js/packages, all packages other than kotlin-css are empty.

**Comment by turansky** [comment]
`@jetbrains/kotlin-css` publication configuration - next step

**Comment by turansky** [comment]
> If you take a look into `build/js/packages`, all packages other than `kotlin-css` are empty.

Now `build/js/packages` not used as NPM source

**Comment by Leonya** [comment]
Can I see what will be published _somewhere_?

**Comment by turansky** [comment]
Draft variant - `build/js/packages/kotlin-wrappers-kotlin-css/kotlin`

**Pull request merged**
